[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Tommaso Bianchi", email = "tommaso.bianchi@polimi.it"},
]
dependencies = [
    "jupyterlab>=3.4.5",
]
requires-python = ">=3.7,<3.8"
license = {text = "MIT"}

[tool.pdm]

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"
